// Package browser launches a web browser routed through a specific SOCKS5
// endpoint using an isolated, throw-away profile so the user's normal
// browsing profile is never modified.
package browser

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
)

// Kind identifies a browser family.
type Kind string

const (
	KindFirefox  Kind = "firefox"
	KindChromium Kind = "chromium" // Chrome, Edge, Brave, Chromium, Vivaldi, Opera
	KindTor      Kind = "torbrowser"
	KindUnknown  Kind = "unknown"
)

// Detected describes an installed browser.
type Detected struct {
	Name string `json:"name"`
	Path string `json:"path"`
	Kind Kind   `json:"kind"`
}

// Classify determines the browser family from its executable path.
func Classify(path string) Kind {
	p := strings.ToLower(filepath.ToSlash(path))
	base := filepath.Base(p)
	switch {
	case strings.Contains(p, "tor browser"):
		return KindTor
	case base == "firefox.exe" || base == "firefox" || strings.Contains(base, "librewolf") || strings.Contains(base, "waterfox"):
		return KindFirefox
	case strings.Contains(base, "chrome") || strings.Contains(base, "msedge") || strings.Contains(base, "brave") ||
		strings.Contains(base, "chromium") || strings.Contains(base, "vivaldi") || strings.Contains(base, "opera"):
		return KindChromium
	default:
		return KindUnknown
	}
}

// Detect returns installed browsers found in standard Windows locations.
func Detect() []Detected {
	pf := os.Getenv("ProgramFiles")
	pf86 := os.Getenv("ProgramFiles(x86)")
	local := os.Getenv("LOCALAPPDATA")
	desktop := filepath.Join(os.Getenv("USERPROFILE"), "Desktop")

	candidates := []struct{ name, path string }{
		{"Tor Browser", filepath.Join(desktop, "Tor Browser", "Browser", "firefox.exe")},
		{"Mozilla Firefox", filepath.Join(pf, "Mozilla Firefox", "firefox.exe")},
		{"Mozilla Firefox", filepath.Join(pf86, "Mozilla Firefox", "firefox.exe")},
		{"Google Chrome", filepath.Join(pf, "Google", "Chrome", "Application", "chrome.exe")},
		{"Google Chrome", filepath.Join(pf86, "Google", "Chrome", "Application", "chrome.exe")},
		{"Google Chrome", filepath.Join(local, "Google", "Chrome", "Application", "chrome.exe")},
		{"Brave", filepath.Join(pf, "BraveSoftware", "Brave-Browser", "Application", "brave.exe")},
		{"Brave", filepath.Join(local, "BraveSoftware", "Brave-Browser", "Application", "brave.exe")},
		{"Microsoft Edge", filepath.Join(pf86, "Microsoft", "Edge", "Application", "msedge.exe")},
		{"Microsoft Edge", filepath.Join(pf, "Microsoft", "Edge", "Application", "msedge.exe")},
		{"Chromium", filepath.Join(local, "Chromium", "Application", "chrome.exe")},
	}

	seen := map[string]bool{}
	var out []Detected
	for _, c := range candidates {
		if c.path == "" || seen[strings.ToLower(c.path)] {
			continue
		}
		if info, err := os.Stat(c.path); err == nil && !info.IsDir() {
			seen[strings.ToLower(c.path)] = true
			out = append(out, Detected{Name: c.name, Path: c.path, Kind: Classify(c.path)})
		}
	}
	return out
}

// FirefoxUserJS returns user.js preferences that route all traffic, including
// DNS, through the SOCKS5 proxy and disable common leak vectors.
func FirefoxUserJS(host string, port int) string {
	prefs := []string{
		`user_pref("network.proxy.type", 1);`,
		fmt.Sprintf(`user_pref("network.proxy.socks", %q);`, host),
		fmt.Sprintf(`user_pref("network.proxy.socks_port", %d);`, port),
		`user_pref("network.proxy.socks_version", 5);`,
		`user_pref("network.proxy.socks_remote_dns", true);`,
		`user_pref("network.proxy.no_proxies_on", "");`,
		`user_pref("network.proxy.allow_hijacking_localhost", true);`,
		`user_pref("network.proxy.failover_direct", false);`,
		`user_pref("network.trr.mode", 5);`,
		`user_pref("network.dns.disablePrefetch", true);`,
		`user_pref("network.prefetch-next", false);`,
		`user_pref("network.predictor.enabled", false);`,
		`user_pref("media.peerconnection.enabled", false);`,
		`user_pref("browser.shell.checkDefaultBrowser", false);`,
		`user_pref("browser.startup.homepage_override.mstone", "ignore");`,
		`user_pref("datareporting.policy.dataSubmissionEnabled", false);`,
		`user_pref("toolkit.telemetry.enabled", false);`,
		`user_pref("app.normandy.enabled", false);`,
	}
	return "// Generated by TorProxyManager — routes this profile through Tor.\n" + strings.Join(prefs, "\n") + "\n"
}

// ChromiumArgs returns command-line flags that force all traffic (and DNS)
// through the SOCKS5 proxy using an isolated profile directory.
func ChromiumArgs(host string, port int, profileDir, startURL string) []string {
	args := []string{
		"--proxy-server=socks5://" + host + ":" + strconv.Itoa(port),
		// Prevent local DNS resolution: everything except the proxy host itself
		// resolves to NOTFOUND locally, so lookups must go through SOCKS5.
		"--host-resolver-rules=MAP * ~NOTFOUND , EXCLUDE " + host,
		"--user-data-dir=" + profileDir,
		"--no-first-run",
		"--no-default-browser-check",
		"--disable-background-networking",
		"--disable-quic",
		"--force-webrtc-ip-handling-policy=disable_non_proxied_udp",
		"--webrtc-ip-handling-policy=disable_non_proxied_udp",
	}
	if startURL != "" {
		args = append(args, startURL)
	}
	return args
}

// Launch starts the browser at path through host:port. profileRoot is a
// directory under which a per-port isolated profile is created.
func Launch(path, host string, port int, profileRoot, startURL string) (*exec.Cmd, error) {
	if path == "" {
		return nil, errors.New("no browser configured or detected")
	}
	if info, err := os.Stat(path); err != nil || info.IsDir() {
		return nil, fmt.Errorf("browser not found: %s", path)
	}

	profileDir := filepath.Join(profileRoot, fmt.Sprintf("port-%d", port))
	if err := os.MkdirAll(profileDir, 0o700); err != nil {
		return nil, fmt.Errorf("create browser profile: %w", err)
	}

	var cmd *exec.Cmd
	switch Classify(path) {
	case KindFirefox:
		if err := os.WriteFile(filepath.Join(profileDir, "user.js"), []byte(FirefoxUserJS(host, port)), 0o600); err != nil {
			return nil, fmt.Errorf("write user.js: %w", err)
		}
		args := []string{"-no-remote", "-profile", profileDir}
		if startURL != "" {
			args = append(args, startURL)
		}
		cmd = exec.Command(path, args...)
	case KindChromium:
		cmd = exec.Command(path, ChromiumArgs(host, port, profileDir, startURL)...)
	case KindTor:
		return nil, errors.New("Tor Browser ships with its own Tor — launch it directly instead of through a SOCKS endpoint")
	default:
		return nil, fmt.Errorf("unsupported browser %q — use Firefox, Chrome, Edge or Brave", filepath.Base(path))
	}

	if err := cmd.Start(); err != nil {
		return nil, fmt.Errorf("launch browser: %w", err)
	}
	go func() { _ = cmd.Wait() }() // reap
	return cmd, nil
}
