// Package torinstance manages individual Tor process lifecycles.
//
// Each Instance owns exactly one tor.exe process with its own torrc, data
// directory, SOCKS port and control port. The lifecycle is:
//
//	stopped -> starting -> bootstrapping -> running
//	                 \            \            \
//	                  +------------+------------+--> failed --(auto-restart)--> starting
//
// A generation counter guards every asynchronous transition so that a Stop()
// issued while a Start() or an auto-restart is in flight always wins and never
// leaves an orphaned process behind.
package torinstance

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"text/template"
	"time"

	"torproxymanager/internal/logger"
	"torproxymanager/internal/winsys"
)

// State represents the lifecycle state of a Tor instance.
type State string

const (
	StateStopped       State = "stopped"
	StateStarting      State = "starting"
	StateBootstrapping State = "bootstrapping"
	StateRunning       State = "running"
	StateFailed        State = "failed"
	StateStopping      State = "stopping"
)

// IsActive reports whether the state represents a live (or launching) process.
func (s State) IsActive() bool {
	return s == StateStarting || s == StateBootstrapping || s == StateRunning
}

// HealthStatus represents the health of a Tor instance's SOCKS endpoint.
type HealthStatus string

const (
	HealthUnknown     HealthStatus = "unknown"
	HealthHealthy     HealthStatus = "healthy"
	HealthUnhealthy   HealthStatus = "unhealthy"
	HealthUnreachable HealthStatus = "unreachable"
)

// ErrAborted is returned by Start when a concurrent Stop cancelled the launch.
var ErrAborted = errors.New("start aborted by stop request")

// Status contains the full status snapshot of a Tor instance.
type Status struct {
	InstanceID        int          `json:"instance_id"`
	SocksPort         int          `json:"socks_port"`
	SocksPortEnd      int          `json:"socks_port_end"`
	PortCount         int          `json:"port_count"`
	ControlPort       int          `json:"control_port"`
	State             State        `json:"state"`
	Health            HealthStatus `json:"health"`
	PID               int          `json:"pid"`
	BootstrapProgress int          `json:"bootstrap_progress"`
	BootstrapSummary  string       `json:"bootstrap_summary,omitempty"`
	StartTime         *time.Time   `json:"start_time,omitempty"`
	UptimeSeconds     float64      `json:"uptime_seconds"`
	StartupDuration   string       `json:"startup_duration,omitempty"`
	StartupMillis     int64        `json:"startup_ms"`
	LastHealthCheck   *time.Time   `json:"last_health_check,omitempty"`
	LastError         string       `json:"last_error,omitempty"`
	RetryCount        int          `json:"retry_count"`
	TotalRestarts     int          `json:"total_restarts"`
	MemoryMB          float64      `json:"memory_mb"`
	CPUPercent        float64      `json:"cpu_percent"`
	ExitIP            string       `json:"exit_ip,omitempty"`
	IsTor             *bool        `json:"is_tor,omitempty"`
	LastExitCheck     *time.Time   `json:"last_exit_check,omitempty"`
	LastNewIdentity   *time.Time   `json:"last_new_identity,omitempty"`
}

// TorrcData holds template values for torrc generation.
type TorrcData struct {
	InstanceID int
	SocksPort  int   // first SOCKS port of this process
	SocksPorts []int // every SOCKS port served by this process
	ControlPort int
	BindAddress string
	DataDir     string
	LogFile     string
	// GeoIPFile / GeoIPv6File are quoted paths to the GeoIP databases shipped
	// next to tor.exe, or "" when none were found.
	GeoIPFile   string
	GeoIPv6File string
}

// findGeoIP locates the GeoIP databases that ship with the Tor Expert Bundle
// (tor\tor.exe + data\geoip) or Tor Browser (Tor\tor.exe + Data\Tor\geoip).
func findGeoIP(torPath string) (v4, v6 string) {
	dir := filepath.Dir(torPath)
	for _, d := range []string{
		filepath.Join(dir, "..", "data"),
		filepath.Join(dir, "..", "Data", "Tor"),
		filepath.Join(dir, "data"),
		dir,
	} {
		p4, p6 := filepath.Join(d, "geoip"), filepath.Join(d, "geoip6")
		if fi, err := os.Stat(p4); err == nil && !fi.IsDir() {
			v4 = quoteTorPath(filepath.ToSlash(filepath.Clean(p4)))
			if fi6, err := os.Stat(p6); err == nil && !fi6.IsDir() {
				v6 = quoteTorPath(filepath.ToSlash(filepath.Clean(p6)))
			}
			return v4, v6
		}
	}
	return "", ""
}

// DefaultTorrcTemplate is used when no external template is configured.
const DefaultTorrcTemplate = `# Auto-generated by TorProxyManager - Instance {{.InstanceID}}
# DO NOT EDIT - this file is regenerated on every start.

# One Tor process, many SOCKS ports. Streams arriving on different SocksPorts
# are never mixed onto the same circuit, so every port is an independent route.
{{range .SocksPorts}}SocksPort {{$.BindAddress}}:{{.}}
{{end}}
ControlPort 127.0.0.1:{{.ControlPort}}
CookieAuthentication 1
DataDirectory {{.DataDir}}

# Client-only: never relay traffic for others.
ClientOnly 1
ExitRelay 0
PublishServerDescriptor 0

# Privacy hardening.
SafeLogging 1
{{if .GeoIPFile}}
# GeoIP databases shipped with Tor (country-based node selection).
GeoIPFile {{.GeoIPFile}}
{{end}}{{if .GeoIPv6File}}GeoIPv6File {{.GeoIPv6File}}
{{end}}
# Log notices to a per-instance file (viewable from the dashboard).
Log notice file {{.LogFile}}
`

// Options configures a new Instance.
type Options struct {
	ID        int
	SocksPort int
	// SocksPortCount is how many consecutive SOCKS ports (starting at
	// SocksPort) this single Tor process serves. Defaults to 1.
	SocksPortCount int
	ControlPort    int
	BindAddress string
	TorPath     string
	DataDir     string

	// TorrcTemplate is the text/template source used to render torrc.
	// Empty means DefaultTorrcTemplate.
	TorrcTemplate string

	ConnTimeout      time.Duration // max time for the SOCKS port to open
	BootstrapTimeout time.Duration // max time to reach 100% bootstrap

	AutoRestart  bool
	RetryLimit   int
	RetryBackoff time.Duration
	BackoffMult  float64
	MaxBackoff   time.Duration

	// OnProcessStarted is invoked with the PID of every launched tor process
	// (used to attach it to the manager's Job Object).
	OnProcessStarted func(pid int)
	// OnChange is invoked (asynchronously safe, non-blocking expected) after
	// every state or health transition.
	OnChange func(Status)
}

// process tracks a single launched tor.exe.
type process struct {
	cmd     *exec.Cmd
	pid     int
	done    chan struct{}
	exitErr error
}

func (p *process) exited() bool {
	select {
	case <-p.done:
		return true
	default:
		return false
	}
}

// Instance manages a single Tor process.
type Instance struct {
	mu   sync.RWMutex
	opts Options
	tmpl *template.Template
	log  *logger.Logger

	gen   uint64 // incremented by every Start/Stop; guards async work
	state State
	proc  *process

	health          HealthStatus
	bootstrap       int
	bootstrapSum    string
	startTime       *time.Time
	startupDuration time.Duration
	lastHealthCheck *time.Time
	lastError       string
	retryCount      int
	totalRestarts   int

	memMB      float64
	cpuPercent float64
	lastCPU    time.Duration
	lastSample time.Time

	exitIP        string
	isTor         *bool
	lastExitCheck *time.Time
	lastNewnym    *time.Time
}

// New creates a new Tor instance. The torrc template is parsed eagerly so
// configuration errors surface before any process is launched.
func New(opts Options, log *logger.Logger) (*Instance, error) {
	if opts.BindAddress == "" {
		opts.BindAddress = "127.0.0.1"
	}
	if opts.SocksPortCount < 1 {
		opts.SocksPortCount = 1
	}
	if opts.ConnTimeout <= 0 {
		opts.ConnTimeout = 30 * time.Second
	}
	if opts.BootstrapTimeout <= 0 {
		opts.BootstrapTimeout = 5 * time.Minute
	}
	if opts.RetryBackoff <= 0 {
		opts.RetryBackoff = 5 * time.Second
	}
	if opts.BackoffMult < 1 {
		opts.BackoffMult = 2
	}
	if opts.MaxBackoff <= 0 {
		opts.MaxBackoff = 5 * time.Minute
	}
	src := opts.TorrcTemplate
	if strings.TrimSpace(src) == "" {
		src = DefaultTorrcTemplate
	}
	tmpl, err := template.New("torrc").Option("missingkey=error").Parse(src)
	if err != nil {
		return nil, fmt.Errorf("torrc template: %w", err)
	}

	return &Instance{
		opts:   opts,
		tmpl:   tmpl,
		log:    log.WithInstance(opts.ID),
		state:  StateStopped,
		health: HealthUnknown,
	}, nil
}

// ID returns the instance ID.
func (inst *Instance) ID() int { return inst.opts.ID }

// SocksPort returns the SOCKS5 port.
func (inst *Instance) SocksPort() int { return inst.opts.SocksPort }

// socksPorts lists every SOCKS port served by this process.
func (inst *Instance) socksPorts() []int {
	ports := make([]int, inst.opts.SocksPortCount)
	for i := range ports {
		ports[i] = inst.opts.SocksPort + i
	}
	return ports
}

// SocksPortEnd returns the last SOCKS5 port served by this process.
func (inst *Instance) SocksPortEnd() int { return inst.opts.SocksPort + inst.opts.SocksPortCount - 1 }

// PortCount returns how many SOCKS5 ports this process serves.
func (inst *Instance) PortCount() int { return inst.opts.SocksPortCount }

// ControlPort returns the control port.
func (inst *Instance) ControlPort() int { return inst.opts.ControlPort }

// DataDir returns the instance data directory.
func (inst *Instance) DataDir() string { return inst.opts.DataDir }

// TorrcPath returns the generated torrc path.
func (inst *Instance) TorrcPath() string { return filepath.Join(inst.opts.DataDir, "torrc") }

// LogPath returns the per-instance Tor log path.
func (inst *Instance) LogPath() string { return filepath.Join(inst.opts.DataDir, "tor.log") }

// PIDFilePath returns the manager-maintained PID file path (used for stale-process cleanup).
func PIDFilePath(dataDir string) string { return filepath.Join(dataDir, "tpm.pid") }

// State returns the current lifecycle state.
func (inst *Instance) State() State {
	inst.mu.RLock()
	defer inst.mu.RUnlock()
	return inst.state
}

// Status returns a snapshot of the instance's current status.
func (inst *Instance) Status() Status {
	inst.mu.RLock()
	defer inst.mu.RUnlock()
	return inst.statusLocked()
}

func (inst *Instance) statusLocked() Status {
	s := Status{
		InstanceID:        inst.opts.ID,
		SocksPort:         inst.opts.SocksPort,
		SocksPortEnd:      inst.opts.SocksPort + inst.opts.SocksPortCount - 1,
		PortCount:         inst.opts.SocksPortCount,
		ControlPort:       inst.opts.ControlPort,
		State:             inst.state,
		Health:            inst.health,
		BootstrapProgress: inst.bootstrap,
		BootstrapSummary:  inst.bootstrapSum,
		RetryCount:        inst.retryCount,
		TotalRestarts:     inst.totalRestarts,
		LastError:         inst.lastError,
		MemoryMB:          inst.memMB,
		CPUPercent:        inst.cpuPercent,
		ExitIP:            inst.exitIP,
		IsTor:             inst.isTor,
	}
	if inst.proc != nil {
		s.PID = inst.proc.pid
	}
	if inst.startTime != nil {
		t := *inst.startTime
		s.StartTime = &t
		if inst.state == StateRunning {
			s.UptimeSeconds = time.Since(t).Seconds()
		}
		s.StartupDuration = inst.startupDuration.Round(time.Millisecond).String()
		s.StartupMillis = inst.startupDuration.Milliseconds()
	}
	if inst.lastHealthCheck != nil {
		t := *inst.lastHealthCheck
		s.LastHealthCheck = &t
	}
	if inst.lastExitCheck != nil {
		t := *inst.lastExitCheck
		s.LastExitCheck = &t
	}
	if inst.lastNewnym != nil {
		t := *inst.lastNewnym
		s.LastNewIdentity = &t
	}
	return s
}

// notify invokes the OnChange callback with a fresh snapshot.
func (inst *Instance) notify() {
	if inst.opts.OnChange != nil {
		inst.opts.OnChange(inst.Status())
	}
}

func (inst *Instance) isCurrent(gen uint64) bool {
	inst.mu.RLock()
	defer inst.mu.RUnlock()
	return inst.gen == gen
}

// Start launches the Tor process and blocks until it is fully bootstrapped,
// fails, times out, ctx is cancelled, or Stop is called.
func (inst *Instance) Start(ctx context.Context) error {
	inst.mu.Lock()
	if inst.state.IsActive() || inst.state == StateStopping {
		st := inst.state
		inst.mu.Unlock()
		return fmt.Errorf("instance %d: already %s", inst.opts.ID, st)
	}
	inst.gen++
	gen := inst.gen
	inst.state = StateStarting
	inst.health = HealthUnknown
	inst.lastError = ""
	inst.bootstrap = 0
	inst.bootstrapSum = ""
	inst.exitIP = ""
	inst.isTor = nil
	inst.mu.Unlock()
	inst.notify()

	err := inst.start(ctx, gen)
	if err != nil && !errors.Is(err, ErrAborted) {
		inst.failIfCurrent(gen, err.Error())
	}
	return err
}

func (inst *Instance) start(ctx context.Context, gen uint64) error {
	inst.log.Debug("Starting Tor (SOCKS %s:%d, control 127.0.0.1:%d)",
		inst.opts.BindAddress, inst.opts.SocksPort, inst.opts.ControlPort)

	if err := os.MkdirAll(inst.opts.DataDir, 0o700); err != nil {
		return fmt.Errorf("create data directory: %w", err)
	}
	// A stale cookie from a previous run would make authentication fail until
	// Tor rewrites it; remove it so we can reliably wait for the fresh one.
	_ = os.Remove(filepath.Join(inst.opts.DataDir, "control_auth_cookie"))

	if err := inst.generateTorrc(); err != nil {
		return fmt.Errorf("generate torrc: %w", err)
	}

	launchedAt := time.Now()
	p, err := inst.launch()
	if err != nil {
		return err
	}

	// Publish the process, unless Stop() raced us — in which case kill it.
	inst.mu.Lock()
	if inst.gen != gen {
		inst.mu.Unlock()
		killAndWait(p, 5*time.Second)
		return ErrAborted
	}
	inst.proc = p
	inst.mu.Unlock()
	inst.notify()

	if err := inst.waitForSocks(ctx, gen, p); err != nil {
		inst.abortProcess(gen, p)
		return err
	}

	inst.setStateIfCurrent(gen, StateBootstrapping)

	if err := inst.waitForBootstrap(ctx, gen, p); err != nil {
		inst.abortProcess(gen, p)
		return err
	}

	now := time.Now()
	dur := now.Sub(launchedAt)

	inst.mu.Lock()
	if inst.gen != gen {
		inst.mu.Unlock()
		return ErrAborted
	}
	inst.state = StateRunning
	inst.health = HealthHealthy
	inst.startTime = &now
	inst.startupDuration = dur
	inst.lastHealthCheck = &now
	inst.mu.Unlock()
	inst.notify()

	inst.log.Info("Ready on 127.0.0.1:%d in %v (PID %d)", inst.opts.SocksPort, dur.Round(time.Millisecond), p.pid)

	go inst.monitor(ctx, gen, p)
	return nil
}

// abortProcess kills a process launched by a failed start attempt.
func (inst *Instance) abortProcess(gen uint64, p *process) {
	killAndWait(p, 5*time.Second)
	inst.mu.Lock()
	if inst.gen == gen && inst.proc == p {
		inst.proc = nil
	}
	inst.mu.Unlock()
}

// StartWithRetry calls Start, retrying failed attempts with exponential backoff
// up to the configured retry limit.
func (inst *Instance) StartWithRetry(ctx context.Context) error {
	var err error
	for attempt := 0; ; attempt++ {
		err = inst.Start(ctx)
		if err == nil || errors.Is(err, ErrAborted) || ctx.Err() != nil {
			return err
		}
		inst.mu.RLock()
		limit := inst.opts.RetryLimit
		st := inst.state
		inst.mu.RUnlock()
		if attempt >= limit || st != StateFailed {
			return err
		}
		delay := inst.backoffFor(attempt)
		inst.log.Warn("Start attempt %d/%d failed: %v — retrying in %v", attempt+1, limit+1, err, delay)

		inst.mu.Lock()
		inst.retryCount = attempt + 1
		inst.mu.Unlock()

		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-time.After(delay):
		}
		// A Stop() during the backoff moves us out of StateFailed.
		if inst.State() != StateFailed {
			return ErrAborted
		}
	}
}

// Stop gracefully shuts down the Tor instance (SIGNAL SHUTDOWN, then kill).
func (inst *Instance) Stop() error {
	inst.mu.Lock()
	if inst.state == StateStopped || inst.state == StateStopping {
		inst.mu.Unlock()
		return nil
	}
	inst.gen++ // invalidates in-flight Start / monitor / restart goroutines
	inst.state = StateStopping
	p := inst.proc
	inst.mu.Unlock()
	inst.notify()

	if p != nil && !p.exited() {
		inst.log.Debug("Stopping (PID %d)", p.pid)
		if err := inst.withControl(func(c *ControlConn) error { return c.Signal("SHUTDOWN") }); err != nil {
			inst.log.Debug("Graceful shutdown via control port failed: %v (will force kill)", err)
		}
		select {
		case <-p.done:
		case <-time.After(5 * time.Second):
			inst.log.Warn("Tor did not exit within 5s, force killing PID %d", p.pid)
			killAndWait(p, 5*time.Second)
		}
	}
	_ = os.Remove(PIDFilePath(inst.opts.DataDir))

	inst.mu.Lock()
	inst.state = StateStopped
	inst.health = HealthUnknown
	inst.proc = nil
	inst.bootstrap = 0
	inst.bootstrapSum = ""
	inst.startTime = nil
	inst.memMB = 0
	inst.cpuPercent = 0
	inst.retryCount = 0
	inst.mu.Unlock()
	inst.notify()
	return nil
}

// Restart stops and starts the instance.
func (inst *Instance) Restart(ctx context.Context) error {
	if err := inst.Stop(); err != nil {
		return fmt.Errorf("restart stop failed: %w", err)
	}
	inst.mu.Lock()
	inst.totalRestarts++
	inst.mu.Unlock()
	return inst.Start(ctx)
}

// NewIdentity sends SIGNAL NEWNYM so that new connections use fresh circuits.
// Tor rate-limits NEWNYM to roughly once every 10 seconds per instance.
func (inst *Instance) NewIdentity() error {
	if st := inst.State(); st != StateRunning {
		return fmt.Errorf("instance %d is %s", inst.opts.ID, st)
	}
	if err := inst.withControl(func(c *ControlConn) error { return c.Signal("NEWNYM") }); err != nil {
		return err
	}
	now := time.Now()
	inst.mu.Lock()
	inst.lastNewnym = &now
	inst.exitIP = "" // exit will change
	inst.isTor = nil
	inst.mu.Unlock()
	inst.notify()
	return nil
}

// CheckHealth performs a SOCKS5 handshake health check and verifies the
// process is still alive.
func (inst *Instance) CheckHealth() HealthStatus {
	inst.mu.RLock()
	if inst.state != StateRunning {
		inst.mu.RUnlock()
		return HealthUnknown
	}
	gen := inst.gen
	p := inst.proc
	timeout := inst.opts.ConnTimeout
	inst.mu.RUnlock()

	status := HealthUnreachable
	if p != nil && !p.exited() {
		status = SOCKS5Handshake(inst.opts.BindAddress, inst.opts.SocksPort, minDur(timeout, 10*time.Second))
	}

	now := time.Now()
	inst.mu.Lock()
	if inst.gen != gen {
		inst.mu.Unlock()
		return HealthUnknown
	}
	changed := inst.health != status
	inst.health = status
	inst.lastHealthCheck = &now
	if status != HealthHealthy {
		inst.lastError = fmt.Sprintf("health check failed: %s", status)
	} else if strings.HasPrefix(inst.lastError, "health check failed") {
		inst.lastError = ""
	}
	inst.mu.Unlock()
	if changed {
		inst.notify()
	}
	return status
}

// RecordExitCheck stores the result of an exit-IP verification.
func (inst *Instance) RecordExitCheck(ip string, isTor bool, checkErr string) {
	now := time.Now()
	inst.mu.Lock()
	inst.lastExitCheck = &now
	if checkErr == "" {
		inst.exitIP = ip
		v := isTor
		inst.isTor = &v
	}
	inst.mu.Unlock()
	inst.notify()
}

// SampleStats refreshes memory and CPU usage of the tor process.
func (inst *Instance) SampleStats() {
	inst.mu.RLock()
	p := inst.proc
	inst.mu.RUnlock()
	if p == nil || p.exited() {
		return
	}
	ws, cpu, err := winsys.ProcessStats(p.pid)
	if err != nil {
		return
	}
	now := time.Now()

	inst.mu.Lock()
	defer inst.mu.Unlock()
	if inst.proc != p {
		return
	}
	inst.memMB = float64(ws) / (1024 * 1024)
	if !inst.lastSample.IsZero() && cpu >= inst.lastCPU {
		wall := now.Sub(inst.lastSample)
		if wall > 0 {
			inst.cpuPercent = float64(cpu-inst.lastCPU) / float64(wall) * 100
		}
	}
	inst.lastCPU = cpu
	inst.lastSample = now
}

// TailLog returns up to maxBytes from the end of the instance's Tor log.
func (inst *Instance) TailLog(maxBytes int64) (string, error) {
	return tailFile(inst.LogPath(), maxBytes)
}

// --- internals ---

func (inst *Instance) setStateIfCurrent(gen uint64, st State) {
	inst.mu.Lock()
	if inst.gen != gen {
		inst.mu.Unlock()
		return
	}
	inst.state = st
	inst.mu.Unlock()
	inst.notify()
}

func (inst *Instance) failIfCurrent(gen uint64, reason string) {
	inst.mu.Lock()
	if inst.gen != gen {
		inst.mu.Unlock()
		return
	}
	inst.state = StateFailed
	inst.health = HealthUnreachable
	inst.lastError = reason
	inst.mu.Unlock()
	inst.log.Warn("Failed: %s", reason)
	inst.notify()
}

// Control opens an authenticated control-port connection and runs fn with it.
func (inst *Instance) Control(fn func(c *ControlConn) error) error {
	return inst.withControl(fn)
}

// withControl opens an authenticated control connection, runs fn, and closes it.
func (inst *Instance) withControl(fn func(c *ControlConn) error) error {
	addr := fmt.Sprintf("127.0.0.1:%d", inst.opts.ControlPort)
	c, err := DialControl(addr, filepath.Join(inst.opts.DataDir, "control_auth_cookie"), 5*time.Second)
	if err != nil {
		return err
	}
	defer c.Close()
	return fn(c)
}

// generateTorrc renders the torrc template for this instance.
func (inst *Instance) generateTorrc() error {
	// Tor accepts forward slashes on Windows and they avoid escaping issues.
	dataDir := filepath.ToSlash(inst.opts.DataDir)
	bind := inst.opts.BindAddress
	switch {
	case strings.EqualFold(bind, "localhost"):
		bind = "127.0.0.1"
	case strings.Contains(bind, ":") && !strings.HasPrefix(bind, "["):
		bind = "[" + bind + "]" // IPv6 literal, e.g. [::1]:9050
	}
	data := TorrcData{
		InstanceID:  inst.opts.ID,
		SocksPort:   inst.opts.SocksPort,
		SocksPorts:  inst.socksPorts(),
		ControlPort: inst.opts.ControlPort,
		BindAddress: bind,
		DataDir:     quoteTorPath(dataDir),
		LogFile:     quoteTorPath(filepath.ToSlash(inst.LogPath())),
	}
	data.GeoIPFile, data.GeoIPv6File = findGeoIP(inst.opts.TorPath)
	var buf bytes.Buffer
	if err := inst.tmpl.Execute(&buf, data); err != nil {
		return err
	}
	return os.WriteFile(inst.TorrcPath(), buf.Bytes(), 0o600)
}

// quoteTorPath quotes a path for torrc if it contains spaces.
func quoteTorPath(p string) string {
	if strings.ContainsAny(p, " \t") {
		return `"` + strings.ReplaceAll(p, `"`, `\"`) + `"`
	}
	return p
}

// launch starts the tor subprocess.
func (inst *Instance) launch() (*process, error) {
	if _, err := os.Stat(inst.opts.TorPath); err != nil {
		return nil, fmt.Errorf("tor executable not found at %s: %w", inst.opts.TorPath, err)
	}

	// Arguments are passed as a vector — never through a shell — so paths
	// cannot inject additional commands.
	cmd := exec.Command(inst.opts.TorPath, "-f", inst.TorrcPath(), "--ignore-missing-torrc")
	cmd.Dir = inst.opts.DataDir
	hideConsoleWindow(cmd)

	out, err := os.Create(filepath.Join(inst.opts.DataDir, "stdout.log"))
	if err != nil {
		return nil, fmt.Errorf("create stdout log: %w", err)
	}
	cmd.Stdout = out
	cmd.Stderr = out

	if err := cmd.Start(); err != nil {
		out.Close()
		return nil, fmt.Errorf("start tor process: %w", err)
	}

	p := &process{cmd: cmd, pid: cmd.Process.Pid, done: make(chan struct{})}
	go func() {
		p.exitErr = cmd.Wait()
		out.Close()
		close(p.done)
	}()

	if inst.opts.OnProcessStarted != nil {
		inst.opts.OnProcessStarted(p.pid)
	}
	_ = os.WriteFile(PIDFilePath(inst.opts.DataDir), []byte(strconv.Itoa(p.pid)), 0o600)

	inst.log.Debug("tor process started (PID %d)", p.pid)
	return p, nil
}

// waitForSocks polls until the SOCKS port accepts TCP connections.
func (inst *Instance) waitForSocks(ctx context.Context, gen uint64, p *process) error {
	deadline := time.NewTimer(inst.opts.ConnTimeout)
	defer deadline.Stop()
	ticker := time.NewTicker(250 * time.Millisecond)
	defer ticker.Stop()

	addr := net.JoinHostPort(inst.opts.BindAddress, strconv.Itoa(inst.opts.SocksPort))
	for {
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-p.done:
			return fmt.Errorf("tor exited during startup (%v)%s", p.exitErr, inst.diagnosticSuffix())
		case <-deadline.C:
			return fmt.Errorf("timeout after %v waiting for SOCKS port %d%s", inst.opts.ConnTimeout, inst.opts.SocksPort, inst.diagnosticSuffix())
		case <-ticker.C:
			if !inst.isCurrent(gen) {
				return ErrAborted
			}
			conn, err := net.DialTimeout("tcp", addr, time.Second)
			if err == nil {
				conn.Close()
				return nil
			}
		}
	}
}

// waitForBootstrap polls the control port until Tor reports PROGRESS=100.
func (inst *Instance) waitForBootstrap(ctx context.Context, gen uint64, p *process) error {
	deadline := time.NewTimer(inst.opts.BootstrapTimeout)
	defer deadline.Stop()
	ticker := time.NewTicker(500 * time.Millisecond)
	defer ticker.Stop()

	var ctl *ControlConn
	defer func() {
		if ctl != nil {
			ctl.Close()
		}
	}()
	addr := fmt.Sprintf("127.0.0.1:%d", inst.opts.ControlPort)
	cookie := filepath.Join(inst.opts.DataDir, "control_auth_cookie")
	lastProgress := -1

	for {
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-p.done:
			return fmt.Errorf("tor exited during bootstrap (%v)%s", p.exitErr, inst.diagnosticSuffix())
		case <-deadline.C:
			inst.mu.RLock()
			pct := inst.bootstrap
			inst.mu.RUnlock()
			return fmt.Errorf("bootstrap timed out after %v at %d%%%s", inst.opts.BootstrapTimeout, pct, inst.diagnosticSuffix())
		case <-ticker.C:
			if !inst.isCurrent(gen) {
				return ErrAborted
			}
			if ctl == nil {
				c, err := DialControl(addr, cookie, 3*time.Second)
				if err != nil {
					continue // cookie not written yet / port not open yet
				}
				ctl = c
			}
			bs, err := ctl.GetBootstrap()
			if err != nil {
				ctl.Close()
				ctl = nil
				continue
			}
			if bs.Progress != lastProgress {
				lastProgress = bs.Progress
				inst.mu.Lock()
				if inst.gen == gen {
					inst.bootstrap = bs.Progress
					inst.bootstrapSum = bs.Summary
				}
				inst.mu.Unlock()
				inst.notify()
				inst.log.Debug("Bootstrap %d%%: %s", bs.Progress, bs.Summary)
			}
			if bs.Progress >= 100 {
				return nil
			}
		}
	}
}

// monitor waits for the process to exit and handles unexpected termination.
func (inst *Instance) monitor(ctx context.Context, gen uint64, p *process) {
	<-p.done

	inst.mu.Lock()
	if inst.gen != gen {
		inst.mu.Unlock()
		return // intentional stop/restart
	}
	uptime := time.Duration(0)
	if inst.startTime != nil {
		uptime = time.Since(*inst.startTime)
	}
	// A long stable run resets the crash-loop counter.
	if uptime > 10*time.Minute {
		inst.retryCount = 0
	}
	inst.state = StateFailed
	inst.health = HealthUnreachable
	inst.proc = nil
	inst.lastError = fmt.Sprintf("tor exited unexpectedly (%v)%s", p.exitErr, inst.diagnosticSuffix())
	autoRestart := inst.opts.AutoRestart
	retry := inst.retryCount
	limit := inst.opts.RetryLimit
	inst.mu.Unlock()

	inst.log.Warn("Tor process %d exited unexpectedly after %v: %v", p.pid, uptime.Round(time.Second), p.exitErr)
	inst.notify()

	if !autoRestart || ctx.Err() != nil {
		return
	}
	if retry >= limit {
		inst.log.Error("Retry limit reached (%d/%d) — not restarting automatically", retry, limit)
		return
	}

	delay := inst.backoffFor(retry)
	inst.mu.Lock()
	inst.retryCount++
	inst.totalRestarts++
	inst.mu.Unlock()
	inst.log.Info("Auto-restarting in %v (attempt %d/%d)", delay, retry+1, limit)

	select {
	case <-ctx.Done():
		return
	case <-time.After(delay):
	}

	// Abort if the instance was stopped/restarted during the backoff.
	if !inst.isCurrent(gen) || inst.State() != StateFailed {
		return
	}
	if err := inst.Start(ctx); err != nil && !errors.Is(err, ErrAborted) {
		inst.log.Error("Auto-restart failed: %v", err)
		// Start's failure leaves us in StateFailed; schedule another attempt.
		inst.mu.RLock()
		newGen := inst.gen
		inst.mu.RUnlock()
		go inst.retryAfterFailure(ctx, newGen)
	}
}

// retryAfterFailure continues the auto-restart loop after a failed restart.
func (inst *Instance) retryAfterFailure(ctx context.Context, gen uint64) {
	inst.mu.Lock()
	if inst.gen != gen || inst.state != StateFailed {
		inst.mu.Unlock()
		return
	}
	retry := inst.retryCount
	limit := inst.opts.RetryLimit
	if retry >= limit {
		inst.mu.Unlock()
		inst.log.Error("Retry limit reached (%d/%d) — not restarting automatically", retry, limit)
		return
	}
	inst.retryCount++
	inst.totalRestarts++
	inst.mu.Unlock()

	delay := inst.backoffFor(retry)
	select {
	case <-ctx.Done():
		return
	case <-time.After(delay):
	}
	if !inst.isCurrent(gen) || inst.State() != StateFailed {
		return
	}
	if err := inst.Start(ctx); err != nil && !errors.Is(err, ErrAborted) {
		inst.mu.RLock()
		newGen := inst.gen
		inst.mu.RUnlock()
		go inst.retryAfterFailure(ctx, newGen)
	}
}

// backoffFor computes the exponential backoff delay for a given attempt (0-based).
func (inst *Instance) backoffFor(attempt int) time.Duration {
	return Backoff(inst.opts.RetryBackoff, inst.opts.BackoffMult, inst.opts.MaxBackoff, attempt)
}

// Backoff returns base * mult^attempt, capped at max.
func Backoff(base time.Duration, mult float64, max time.Duration, attempt int) time.Duration {
	d := float64(base)
	for i := 0; i < attempt; i++ {
		d *= mult
		if time.Duration(d) >= max {
			return max
		}
	}
	if time.Duration(d) > max {
		return max
	}
	return time.Duration(d)
}

// diagnosticSuffix extracts the most relevant recent Tor log lines.
func (inst *Instance) diagnosticSuffix() string {
	var picked []string
	for _, f := range []string{inst.LogPath(), filepath.Join(inst.opts.DataDir, "stdout.log")} {
		tail, err := tailFile(f, 4096)
		if err != nil || tail == "" {
			continue
		}
		lines := strings.Split(strings.TrimSpace(tail), "\n")
		for i := len(lines) - 1; i >= 0 && len(picked) < 2; i-- {
			l := strings.TrimSpace(lines[i])
			if strings.Contains(l, "[warn]") || strings.Contains(l, "[err]") {
				picked = append([]string{l}, picked...)
			}
		}
		if len(picked) > 0 {
			break
		}
	}
	if len(picked) == 0 {
		return ""
	}
	return " — " + strings.Join(picked, " | ")
}

// SOCKS5Handshake performs a no-auth SOCKS5 greeting and validates the reply.
func SOCKS5Handshake(host string, port int, timeout time.Duration) HealthStatus {
	conn, err := net.DialTimeout("tcp", net.JoinHostPort(host, strconv.Itoa(port)), timeout)
	if err != nil {
		return HealthUnreachable
	}
	defer conn.Close()
	_ = conn.SetDeadline(time.Now().Add(timeout))

	if _, err := conn.Write([]byte{0x05, 0x01, 0x00}); err != nil {
		return HealthUnhealthy
	}
	resp := make([]byte, 2)
	if _, err := io.ReadFull(conn, resp); err != nil {
		return HealthUnhealthy
	}
	if resp[0] != 0x05 || resp[1] != 0x00 {
		return HealthUnhealthy
	}
	return HealthHealthy
}

func killAndWait(p *process, timeout time.Duration) {
	if p == nil || p.exited() {
		return
	}
	_ = p.cmd.Process.Kill()
	select {
	case <-p.done:
	case <-time.After(timeout):
	}
}

func tailFile(path string, maxBytes int64) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()
	info, err := f.Stat()
	if err != nil {
		return "", err
	}
	start := info.Size() - maxBytes
	if start < 0 {
		start = 0
	}
	buf := make([]byte, info.Size()-start)
	if _, err := f.ReadAt(buf, start); err != nil && err != io.EOF {
		return "", err
	}
	s := string(buf)
	if start > 0 {
		if i := strings.IndexByte(s, '\n'); i >= 0 {
			s = s[i+1:] // drop the partial first line
		}
	}
	return s, nil
}

func minDur(a, b time.Duration) time.Duration {
	if a < b {
		return a
	}
	return b
}
